######### CONFIGURACIÓN BASE###############################################
##      Acá se almacenan datos de configuración base.                    ##
## Es recomendable no hacer los cambios desde este archivo directamente  ##
## si no por medio del editor de CMS.                                    ##
##                                                                       ##
###########################################################################


#NOMBRE DE LA MARCA
name: Pratyaksa Yoga

#TITULO PRINCIPAL QUE FIGURA EN LAS PESTAÑAS
title: Pratyaksa | Centro de Yoga

#CORREO ELECTRONICO DEL SITIO WEB
email: pratyaksayoga@gmail.com

#DESCRIPCION QUE FIGURA EN LA BUSQUEDA DE GOOGLE
description: Clases de Yoga en Boedo y Almagro

#Social
#twitter_username: 
#github_username:  



#########NO MODIFICAR#######################################
#DIRECCION BASE                                            #
baseurl: "/" # the subpath of your site, e.g. /blog        #
#                                                          #
#DOMINIO DEL SITIO WEB                                     #
#url: "https://pratyaksayoga.github.io"                     #
url: "https://pratyaksayoga.com.ar"
#                                                          # 
# Build settings                                           #
theme: minima                                              #
#                                                          #
#Material Design Bootstrap                                 # 
mdb: true                                                  #
#                                                          #
plugins:                                                   #
  - jekyll-feed                                            #
  - jekyll-sitemap                                         #
  - jekyll-seo-tag                                         #
#                                                          #
#Lets to publish future posts dates                        #
future: true                                               #  
#                                                          #
#Collections                                               #
collections:                                               #
  eventos:                                                 #
    output: true                                           #
#                                                          #
  clases:                                                  #
    output: true                                           #
#                                                          #
  equipo:                                                  #
    output: false                                          #
#                                                          #
  galeria:                                                 #
    output: false                                          #
#                                                          #  
  testimonios:                                             #
    output: false                                          #
##################                                         #
defaults:                                                  #
  - scope:                                                 #
      path: ""                                             #
      type: "eventos"                                      #
    values:                                                #
      layout: "eventos"                                    #
  - scope:                                                 #
      path: ""                                             #
      type: "clases"                                       #
    values:                                                #
      layout: "clases"                                     #
############################################################

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


