---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Configuración General
- type: document
  path: _data/navigation.yml
  label: Barra de navegación
- type: document
  path: _data/secciones.yml
  label: Secciones
- type: document
  path: _data/redes.yml
  label: Datos de Contacto
- type: document
  path: _data/footer.yml
  label: Pie de Página
- type: jekyll-pages
  label: Páginas (Principal, Galería, Novedades)
  create: all
- type: heading
  label: Contenido
- type: directory
  path: _clases
  label: Clases
  create: all
  match: "**/*"
- type: directory
  path: _eventos
  label: Eventos
  create: all
  match: "**/*"
- type: document
  path: _data/horario.yml
  label: Horario
- type: directory
  path: _testimonios
  label: Testimonios
  create: all
  match: "**/*"
- type: directory
  path: _galeria
  label: Galeria
  create: all
  match: "**/*"
- type: directory
  path: _equipo
  label: Equipo
  create: all
  match: "**/*"
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 4001 --host 0.0.0.0 -d _site
